version: '2'

services:
  db:
    container_name: mysql
    image: library/mysql
    restart: always
    networks:
      test:
        ipv4_address: 182.21.0.49
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: loadbalance
    depends_on:
      - web1
      - web2
      - web3
    restart: always
    ports:
      - "9090:80"
    networks:
      test:
        ipv4_address: 182.21.0.50 
    

  web1:
    container_name: web1
    image: library/drupal
    depends_on: 
      - db
    restart: always
    ports:
      - "9091:80"
    networks:
      test:
        ipv4_address: 182.21.0.20

  web2:
    container_name: web2
    image: library/drupal
    depends_on: 
      - db
    restart: always
    ports:
      - "9092:80"
    networks:
      test:
        ipv4_address: 182.21.0.21

  web3:
    container_name: web3
    image: library/drupal
    depends_on: 
      - db
    restart: always
    ports:
      - "9093:80"
    networks:
      test:
        ipv4_address: 182.21.0.22

networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 182.21.0.0/24
          gateway: 182.21.0.1
