version: '2'

services:
  db:
    container_name: database
    image: mis_img/mysql:v8
    restart: always
    ports:
      - "3360:3306"
    networks:
      drupal_stack:
        ipv4_address: 172.20.0.18
    environment:
      TZ: Europe/Madrid
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: drupal
      MYSQL_USER: daniel
      MYSQL_PASSWORD: daniel
    volumes:
      - mysql_data:/var/lib/mysql


  nginx:
    container_name: nginx
    image: mis_img/loadbalancer:v2
    restart: always
    ports:
      - "9090:80"
    networks:
      drupal_stack:
        ipv4_address: 172.20.0.19
    environment:
      TZ: Europe/Madrid
      WEB1: 172.20.0.20
      WEB2: 172.20.0.21
      WEB3: 172.20.0.22
      WEB4: 172.20.0.23


  web1:
    container_name: web1
    image: library/drupal:8
    depends_on:
      - db
    restart: always
    ports:
      - "9091:80"
    volumes:
      - drupal_data:/var/www/html
    environment:
      TZ: Europe/Madrid
    networks:
      drupal_stack:
        ipv4_address: 172.20.0.20

  web2:
    container_name: web2
    image: library/drupal:8
    depends_on:
      - db
    restart: always
    ports:
      - "9092:80"
    volumes:
      - drupal_data:/var/www/html
    environment:
      TZ: Europe/Madrid
    networks:
      drupal_stack:
        ipv4_address: 172.20.0.21

  web3:
    container_name: web3
    image: library/drupal:8
    depends_on:
      - db
    restart: always
    ports:
      - "9093:80"
    volumes:
      - drupal_data:/var/www/html
    environment:
      TZ: Europe/Madrid
    networks:
      drupal_stack:
        ipv4_address: 172.20.0.22


volumes:
  mysql_data:
  drupal_data:

networks:
  drupal_stack:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
