version: '2'

services:
  db:
    container_name: database
    image: mio/mysql
    restart: always
    networks:
      drupal:
        ipv4_address: 172.20.0.18
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: my_images/loadbalancer
    restart: always
    ports:
      - "9090:80"
    networks:
      drupal:
        ipv4_address: 172.20.0.19


  web1:
    container_name: web1
    image: library/drupal:8
    depends_on:
      - db
    restart: always
    ports:
      - "9091:80"
    networks:
      drupal:
        ipv4_address: 172.20.0.20

  web2:
    container_name: web2
    image: library/drupal:8
    depends_on:
      - db
    restart: always
    ports:
      - "9092:80"
    networks:
      drupal:
        ipv4_address: 172.20.0.21

  web3:
    container_name: web3
    image: library/drupal:8
    depends_on:
      - db
    restart: always
    ports:
      - "9093:80"
    volumes:
      - drupal_data:/var/www/html
    networks:
      drupal:
        ipv4_address: 172.20.0.22


volumes:
  db_data:
  drupal_data:

networks:
  drupal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
